### PR TITLE
include scopes in refresh tokens

### PR DESCRIPTION
**Pull request by nquandt**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

I noticed that when using scopes in auth0 that NOT including a scope param in the body of a refresh token request causes the access token returned to not have the same scope. Not sure if feature or bug. This change allows for the scope inclusion to be an opt-in (as otherwise I believe it would be considered a breaking change).

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

### CODE REVIEW

**Comment by nquandt** [comment]
I submitted this looking for a bit of feedback / am open to ideas. I don't know that this is the correct fix (or if something is wrong on the actual auth0 side) I was under the impression refresh tokens should create new access tokens with the same scopes as before

**Comment by frederikprijck** [comment]
Refresh tokens should return access tokens using the same scopes, there is no need to pass along the scopes if all you want is to retrieve a token using the original scopes.

Is there perhaps some action/rules in Auth0 that's relying on the existence of that scope paramter?

**Comment by nquandt** [comment]
I will triple check our configuration and if I can’t find a reason i will try to prepare a repro for testing purposes, probably in the next couple days. 

Thanks!

**Comment by frederikprijck** [comment]
Closing this, feel free to open an issue if you need further assistance.

**Comment by sizzle168** [comment]
Hey @frederikprijck, I know the issue is already closed, but we have exactly this use case in our project that the scopes are needed on refresh to enrich the token with custom claims. So this solution would have helped us. Are there any other possible solutions to solve this?

**Comment by frederikprijck** [comment]
You should be able to use a custom parameter for that, and not rely on using the scope property for something it's not intended for.

**Comment by sizzle168** [comment]
And how can I add a custom parameter to the refresh-token-request?

**Comment by frederikprijck** [comment]
All HTTP calls are done using the Backchannel that you can configure when registering our SDK, you can use this backchannel to intercept any HTTP calls and modify requests as needed through the Http Message Handler, more info https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers.

**Comment by sizzle168** [comment]
Ok, thanks! We now managed to solve this by setting the BackchannelHttpHandler. Would be nice if this options was also provided by this library and passed through to oidc.

**Pull request closed without merging**
